console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    powerline_symbol = "\ue0b0"
    background = 'transparent'
    foreground = 'blue'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#6c6c6c'
    background = 'transparent'
    template = ' {{ .HEAD }}{{if or (.Working.Changed) (.Staging.Changed) }}*{{end}} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'
  
    [blocks.segments.properties]
      branch_icon = ''
      fetch_status = true
      commit_icon = '@'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    background = 'transparent'
    foreground = 'magenta'
    template = "\uf061"
